version: "3"

services:
  api:
    build: ./packages/api
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      API_PORT: ${API_PORT}

  web:
    build:
      context: ./packages/web
      args:
        API_URI: http://${API_HOST}:${API_PORT}
    ports:
      - ${WEB_PORT}:3000
    depends_on:
      - api

  # Run e2e tests locally via Docker:
  # This is normally useless since it's faster to run it via these commands:
  # - `docker-compose up --build -d api`
  # - `docker-compose up --build -d web`
  # - `yarn e2e`
  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    links:
      - docker-dind
    environment:
      DOCKER_HOST: tcp://docker-dind:2375
      WEB_URI: http://web:3000
    depends_on:
      - web

  # This is required in order to enable docker-in-docker when running the "test" service locally:
  docker-dind:
    image: docker:dind
    privileged: true
    expose:
      - 2375
